import { Request, Response, NextFunction } from 'express';
import { config } from '../utils/config';
import { createError } from './errorHandler';
import { authService } from '../services/authService';
import { logger } from '../utils/logger';

// Extend Request interface to include user data
declare global {
  namespace Express {
    interface Request {
      user?: {
        userId: string;
        userData?: any;
      };
    }
  }
}

/**
 * Legacy API Key authentication (deprecated)
 * Use jwtAuth for new implementations
 */
export const apiKeyAuth = (req: Request, res: Response, next: NextFunction): void => {
  // Skip auth in development if no API key is set
  if (config.nodeEnv === 'development' && !config.apiKey) {
    logger.warn('API Key authentication skipped in development mode');
    return next();
  }

  const apiKey = req.headers['x-api-key'] || req.query.apiKey;

  if (!apiKey) {
    throw createError('API key is required', 401);
  }

  if (apiKey !== config.apiKey) {
    logger.warn('Invalid API key attempt', {
      providedKey: String(apiKey).substring(0, 8) + '...',
      ip: req.ip,
      userAgent: req.get('User-Agent')
    });
    throw createError('Invalid API key', 401);
  }

  logger.debug('API key authentication successful');
  next();
};

/**
 * JWT Authentication middleware
 * Validates JWT tokens generated by our auth service
 */
export const jwtAuth = (req: Request, res: Response, next: NextFunction): void => {
  try {
    const authHeader = req.headers.authorization;

    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      logger.warn('Missing or invalid Authorization header', {
        hasHeader: !!authHeader,
        headerStart: authHeader?.substring(0, 10),
        ip: req.ip,
        path: req.path
      });
      throw createError('Missing or invalid Authorization header. Use: Authorization: Bearer <token>', 401);
    }

    const token = authHeader.substring(7);

    if (!token) {
      throw createError('JWT token is required', 401);
    }

    // Verify JWT token
    const decoded = authService.verifyJWT(token);

    if (!decoded) {
      logger.warn('Invalid JWT token provided', {
        tokenStart: token.substring(0, 20) + '...',
        ip: req.ip,
        path: req.path
      });
      throw createError('Invalid or expired JWT token', 401);
    }

    // Check if user has access to reports
    if (!authService.hasReportsAccess(decoded.userId)) {
      logger.warn('User does not have reports access', {
        userId: decoded.userId,
        ip: req.ip,
        path: req.path
      });
      throw createError('Insufficient permissions for reports service', 403);
    }

    // Add user info to request object
    req.user = {
      userId: decoded.userId,
      userData: (decoded as any).userData
    };

    logger.debug('JWT authentication successful', {
      userId: decoded.userId,
      path: req.path
    });

    next();

  } catch (error) {
    if (error instanceof Error && error.message.includes('required')) {
      // Re-throw our custom errors
      throw error;
    }
    
    logger.error('JWT authentication error', {
      error: error instanceof Error ? error.message : String(error),
      ip: req.ip,
      path: req.path
    });
    
    throw createError('Authentication failed', 401);
  }
};

/**
 * Optional JWT Authentication
 * Adds user info if valid JWT is provided, but doesn't require it
 */
export const optionalJwtAuth = (req: Request, res: Response, next: NextFunction): void => {
  try {
    const authHeader = req.headers.authorization;

    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      // No auth provided, continue without user info
      return next();
    }

    const token = authHeader.substring(7);
    const decoded = authService.verifyJWT(token);

    if (decoded && authService.hasReportsAccess(decoded.userId)) {
      req.user = {
        userId: decoded.userId,
        userData: (decoded as any).userData
      };

      logger.debug('Optional JWT authentication successful', {
        userId: decoded.userId,
        path: req.path
      });
    }

    next();

  } catch (error) {
    // In optional auth, we don't fail on auth errors
    logger.debug('Optional JWT authentication failed, continuing without auth', {
      error: error instanceof Error ? error.message : String(error),
      path: req.path
    });
    
    next();
  }
};

/**
 * Hybrid authentication middleware
 * Accepts either API Key (legacy) or JWT token (new)
 */
export const hybridAuth = (req: Request, res: Response, next: NextFunction): void => {
  try {
    const authHeader = req.headers.authorization;
    const apiKey = req.headers['x-api-key'] || req.query.apiKey;

    // Try JWT first
    if (authHeader && authHeader.startsWith('Bearer ')) {
      return jwtAuth(req, res, next);
    }

    // Fall back to API Key
    if (apiKey) {
      return apiKeyAuth(req, res, next);
    }

    // No authentication provided
    logger.warn('No authentication provided', {
      ip: req.ip,
      path: req.path,
      userAgent: req.get('User-Agent')
    });

    throw createError('Authentication required. Provide either JWT token (Authorization: Bearer <token>) or API key (X-API-Key: <key>)', 401);

  } catch (error) {
    throw error;
  }
};