version: "3.8"

services:
  reports:
    build:
      context: .
      dockerfile: Dockerfile
    image: formarte-reports:latest
    container_name: formarte-reports
    ports:
      - "3350:3350"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3350
      HOST: 0.0.0.0
    volumes:
      - pdfs:/app/public/pdfs
    restart: unless-stopped
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  pdfs:
